<a href="https://colab.research.google.com/github/sagarbhadra7/Python-Programs/blob/master/sys_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import sys

In [2]:
sys.getdefaultencoding()

'utf-8'

In [0]:
import numpy as np

In [5]:
np.empty((4,5))

array([[1.78864886e-316, 5.38531554e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [1.16095484e-028, 3.68423986e+180, 5.56218858e+180,
        1.54722523e+262, 7.48952651e+247],
       [8.76739466e+252, 8.89489936e+252, 1.17149199e+214,
        1.14428494e+243, 1.35617218e+248],
       [2.78225511e+296, 7.67127212e+151, 2.77620488e+184,
        2.66090405e-312, 0.00000000e+000]])

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
print(np.ones_like((2,3)))

[1 1]


In [8]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.identity(1)

array([[1.]])